version: '3.9'

services:

  redis:
    image: redis:7.2.2-alpine
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

  

  db:
    restart: always
    image: postgres:14.7-alpine
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5 

  app:
    container_name: app
    build: .
    env_file:
      - .env
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8080:8000'

  celery:
    build: .
    container_name: celery
    command: >
      bash -c "celery -A config worker --beat --loglevel=info"
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - app
      - redis


volumes:
  postgres_data:
  redis_data: